//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begemotik.Data.Job
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public System.Guid JobId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public System.DateTime Completed { get; set; }
        public byte Status { get; set; }
        public int HijackId { get; set; }
    }
}
